ci_service: travis_ci
coverage_service: coveralls
workspace: DragDropUI.xcworkspace
xcodeproj: DragDropUI.xcodeproj
scheme: DragDropUI
source_directory: Source/
ignore:
  - DragDropUI/AppDelegate.swift
  - DragDropUI/ViewController.swift