language: objective-c
osx_image: xcode8
xcode_project: DragDropUI.xcworkspace
xcode_scheme: DragDropUITests
xcode_sdk: iphonesimulator10.0

branches:
 only:
 - master

before_install:
- rm -rf /Users/travis/Library/Developer/Xcode/DerivedData/DragDropUI-*/
- rvm use $RVM_RUBY_VERSION

install:
- bundle
- bundle install --without=documentation --path ../travis_bundle_dir

script:
- xcodebuild -workspace DragDropUI.xcworkspace -scheme DragDropUI -destination "platform=iOS Simulator,name=iPhone 6s,OS=10.0" clean test | xcpretty

after_success: slather